---
- hosts: webservers
  tasks:
    - name: code source via git
      git:                                            // <1>
        repo: "https://github.com/rauchg/slackin.git" // <2>
        dest: "{{ ansible_env.HOME }}"
        clone: yes                                    // <3>
        update: yes                                   // <4>
    - name: mise à jour des modules npm
      npm:                                            // <5>
        state: present                                // <6>
        path: "{{ ansible_env.HOME }}"
        production: true                              // <7>
