FROM registry.fedoraproject.org/fedora-minimal

LABEL Maintainer="https://gitlab.com/users/franckf/"
LABEL Description="minimal restful api"

RUN \
  microdnf --assumeyes install nodejs && \
  microdnf --assumeyes install sqlite

WORKDIR /home/node/app

COPY package*.json ./

RUN npm install --production

COPY . .

EXPOSE 3000

CMD [ "node", "index.js" ]